### ISSUE TITLE
facet-processor_clock error: Invalid type :bytes16

### ISSUE THREAD

**Issue by dubuqingfeng** [0xFacet/facet-vm#166]
```
facet-processor_clock    | /app/app/models/contract_transaction.rb:29:in `create_from_ethscription!'
facet-processor_clock    | /app/app/models/ethscription.rb:47:in `block in process!'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/transactions.rb:212:in `transaction'
facet-processor_clock    | /app/app/models/ethscription.rb:36:in `process!'
facet-processor_clock    | /app/app/models/eth_block.rb:87:in `block (2 levels) in process_contract_actions_for_next_block_with_ethscriptions'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
facet-processor_clock    | /app/app/models/eth_block.rb:86:in `block in process_contract_actions_for_next_block_with_ethscriptions'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
facet-processor_clock    | /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/transactions.rb:212:in `transaction'
facet-processor_clock    | /app/app/models/eth_block.rb:70:in `process_contract_actions_for_next_block_with_ethscriptions'
facet-processor_clock    | /app/app/models/eth_block.rb:37:in `block in process_contract_actions_until_done'
facet-processor_clock    | /app/app/models/eth_block.rb:34:in `loop'
facet-processor_clock    | /app/app/models/eth_block.rb:34:in `process_contract_actions_until_done'
facet-processor_clock    | /app/config/processor_clock.rb:25:in `block in <module:Clockwork>'
facet-processor_clock    | /usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/event.rb:61:in `execute'
facet-processor_clock    | /usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/event.rb:48:in `run'
facet-processor_clock    | /usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:136:in `block in tick'
facet-processor_clock    | /usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:134:in `each'
facet-processor_clock    | /usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:134:in `tick'
facet-processor_clock    | /usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:123:in `block (2 levels) in run_tick_loop'
facet-processor_clock    | /usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:121:in `synchronize'
facet-processor_clock    | /usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:121:in `block in run_tick_loop'
facet-processor_clock    | I, [2024-01-14T02:15:46.087975 #1]  INFO -- : Finished 'EthBlock.process_contract_actions_until_done' duration_ms=87 error=#<TypeError: Invalid type :bytes16>
facet-processor_clock    | I, [2024-01-14T02:15:47.001139 #1]  INFO -- : Triggering 'EthBlock.process_contract_actions_until_done'
facet-processor_clock    | E, [2024-01-14T02:15:47.088485 #1] ERROR -- : Invalid type :bytes16 (TypeError)
facet-processor_clock    | /app/lib/rubidity/type_system/type.rb:46:in `initialize'
facet-processor_clock    | /app/lib/rubidity/type_system/type.rb:56:in `new'
facet-processor_clock    | /app/lib/rubidity/type_system/type.rb:56:in `create'
facet-processor_clock    | /app/lib/rubidity/type_system/type.rb:61:in `key_type='
facet-processor_clock    | /app/lib/rubidity/type_system/type.rb:70:in `metadata='
facet-processor_clock    | /app/lib/rubidity/type_system/type.rb:50:in `initialize'
facet-processor_clock    | /app/lib/rubidity/type_system/type.rb:56:in `new'
facet-processor_clock    | /app/lib/rubidity/type_system/type.rb:56:in `create'
facet-processor_clock    | /app/lib/rubidity/contract_implementation.rb:51:in `mapping'
facet-processor_clock    | FacetPortV1:233:in `block in instance_eval_with_isolation'
facet-processor_clock    | /app/lib/rubidity/transpiler/contract_builder.rb:59:in `block in contract'
facet-processor_clock    | /app/lib/rubidity/transpiler/contract_builder.rb:43:in `initialize'
facet-processor_clock    | /app/lib/rubidity/transpiler/contract_builder.rb:43:in `new'
facet-processor_clock    | /app/lib/rubidity/transpiler/contract_builder.rb:43:in `contract'
facet-processor_clock    | FacetPortV1:228:in `instance_eval_with_isolation'
facet-processor_clock    | /app/lib/rubidity/transpiler/contract_builder.rb:23:in `instance_eval'
facet-processor_clock    | /app/lib/rubidity/transpiler/contract_builder.rb:23:in `instance_eval_with_isolation'
facet-processor_clock    | /app/lib/rubidity/transpiler/contract_builder.rb:7:in `block in build_contract_class'
facet-processor_clock    | /app/lib/rubidity/transpiler/contract_builder.rb:5:in `each'
facet-processor_clock    | /app/lib/rubidity/transpiler/contract_builder.rb:5:in `build_contract_class'
facet-processor_clock    | /app/app/models/contract_artifact.rb:61:in `build_class'
facet-processor_clock    | /usr/local/bundle/gems/memoist-0.16.2/lib/memoist.rb:213:in `build_class'
facet-processor_clock    | /app/app/models/contract_artifact.rb:107:in `build_class'
facet-processor_clock    | /app/lib/rubidity/transaction_execution/transaction_context.rb:111:in `create_artifact_and_build_class'
facet-processor_clock    | /app/lib/rubidity/transaction_execution/transaction_context.rb:43:in `supported_contract_class'
facet-processor_clock    | /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:184:in `supported_contract_class'
facet-processor_clock    | /app/app/models/contract_call.rb:100:in `create_and_validate_new_contract!'
facet-processor_clock    | /app/app/models/contract_call.rb:26:in `execute!'
facet-processor_clock    | /app/lib/rubidity/transaction_execution/call_stack.rb:72:in `execute_in_frame'
facet-processor_clock    | /app/lib/rubidity/transaction_execution/call_stack.rb:53:in `block in execute_in_new_frame'
facet-processor_clock    | /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:214:in `set'
facet-processor_clock    | /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:156:in `set'
facet-processor_clock    | /app/lib/rubidity/transaction_execution/call_stack.rb:52:in `execute_in_new_frame'
facet-processor_clock    | /app/app/models/contract_transaction.rb:250:in `block in make_initial_call'
facet-processor_clock    | /app/app/models/contract_transaction.rb:242:in `block in with_global_context'
facet-processor_clock    | /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:214:in `set'
facet-processor_clock    | /usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:156:in `set'
facet-processor_clock    | /app/app/models/contract_transaction.rb:229:in `with_global_context'
facet-processor_clock    | /app/app/models/contract_transaction.rb:247:in `make_initial_call'
facet-processor_clock    | /app/app/models/contract_transaction.rb:269:in `execute_transaction'
facet-processor_clock    | /app/app/models/contract_transaction.rb:30:in `block in create_from_ethscription!'
facet-processor_clock    | <internal:kernel>:90:in `tap'
facet-processor_clock    | /app/app/models/contract_transaction.rb:29:in `create_from_ethscription!'
facet-processor_clock    | /app/app/models/ethscription.rb:47:in `block in process!'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/transactions.rb:212:in `transaction'
facet-processor_clock    | /app/app/models/ethscription.rb:36:in `process!'
facet-processor_clock    | /app/app/models/eth_block.rb:87:in `block (2 levels) in process_contract_actions_for_next_block_with_ethscriptions'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
facet-processor_clock    | /app/app/models/eth_block.rb:86:in `block in process_contract_actions_for_next_block_with_ethscriptions'
facet-processor_clock    | /usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
```

**Comment by dubuqingfeng** [comment]
The block has stopped at "blocknumber": "19000377",

I think we need to update the version.

**Comment by dubuqingfeng** [comment]
The issue occurred after the update was completed



```
E, [2024-01-14T02:32:20.015062 #1] ERROR -- : unknown attribute 'call_level' for ContractCall. (ActiveModel::UnknownAttributeError)
/usr/local/bundle/gems/activemodel-7.1.2/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/attribute_assignment.rb:19:in `block in _assign_attributes'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/attribute_assignment.rb:11:in `each'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/attribute_assignment.rb:11:in `_assign_attributes'
/usr/local/bundle/gems/activemodel-7.1.2/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/core.rb:432:in `initialize'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/inheritance.rb:76:in `new'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/inheritance.rb:76:in `new'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/reflection.rb:176:in `build_association'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/associations/association.rb:352:in `build_record'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/associations/collection_association.rb:119:in `build'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/associations/collection_proxy.rb:319:in `build'
/app/lib/rubidity/transaction_execution/call_stack.rb:42:in `execute_in_new_frame'
/app/app/models/contract_transaction.rb:250:in `block in make_initial_call'
/app/app/models/contract_transaction.rb:242:in `block in with_global_context'
/usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:214:in `set'
/usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:156:in `set'
/app/app/models/contract_transaction.rb:229:in `with_global_context'
/app/app/models/contract_transaction.rb:247:in `make_initial_call'
/app/app/models/contract_transaction.rb:269:in `execute_transaction'
/app/app/models/contract_transaction.rb:30:in `block in create_from_ethscription!'
<internal:kernel>:90:in `tap'
/app/app/models/contract_transaction.rb:29:in `create_from_ethscription!'
/app/app/models/ethscription.rb:47:in `block in process!'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/transactions.rb:212:in `transaction'
/app/app/models/ethscription.rb:36:in `process!'
/app/app/models/eth_block.rb:87:in `block (2 levels) in process_contract_actions_for_next_block_with_ethscriptions'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
/app/app/models/eth_block.rb:86:in `block in process_contract_actions_for_next_block_with_ethscriptions'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/transactions.rb:212:in `transaction'
/app/app/models/eth_block.rb:70:in `process_contract_actions_for_next_block_with_ethscriptions'
/app/app/models/eth_block.rb:37:in `block in process_contract_actions_until_done'
/app/app/models/eth_block.rb:34:in `loop'
/app/app/models/eth_block.rb:34:in `process_contract_actions_until_done'
/app/config/processor_clock.rb:25:in `block in <module:Clockwork>'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/event.rb:61:in `execute'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/event.rb:48:in `run'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:136:in `block in tick'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:134:in `each'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:134:in `tick'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:123:in `block (2 levels) in run_tick_loop'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:121:in `synchronize'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:121:in `block in run_tick_loop'
I, [2024-01-14T02:32:20.015425 #1]  INFO -- : Finished 'EthBlock.process_contract_actions_until_done' duration_ms=14 error=#<ActiveModel::UnknownAttributeError: unknown attribute 'call_level' for ContractCall.>
I, [2024-01-14T02:32:21.001138 #1]  INFO -- : Triggering 'EthBlock.process_contract_actions_until_done'
E, [2024-01-14T02:32:21.014723 #1] ERROR -- : unknown attribute 'call_level' for ContractCall. (ActiveModel::UnknownAttributeError)
/usr/local/bundle/gems/activemodel-7.1.2/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/attribute_assignment.rb:19:in `block in _assign_attributes'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/attribute_assignment.rb:11:in `each'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/attribute_assignment.rb:11:in `_assign_attributes'
/usr/local/bundle/gems/activemodel-7.1.2/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/core.rb:432:in `initialize'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/inheritance.rb:76:in `new'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/inheritance.rb:76:in `new'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/reflection.rb:176:in `build_association'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/associations/association.rb:352:in `build_record'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/associations/collection_association.rb:119:in `build'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/associations/collection_proxy.rb:319:in `build'
/app/lib/rubidity/transaction_execution/call_stack.rb:42:in `execute_in_new_frame'
/app/app/models/contract_transaction.rb:250:in `block in make_initial_call'
/app/app/models/contract_transaction.rb:242:in `block in with_global_context'
/usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:214:in `set'
/usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:156:in `set'
/app/app/models/contract_transaction.rb:229:in `with_global_context'
/app/app/models/contract_transaction.rb:247:in `make_initial_call'
/app/app/models/contract_transaction.rb:269:in `execute_transaction'
/app/app/models/contract_transaction.rb:30:in `block in create_from_ethscription!'
<internal:kernel>:90:in `tap'
/app/app/models/contract_transaction.rb:29:in `create_from_ethscription!'
/app/app/models/ethscription.rb:47:in `block in process!'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/transactions.rb:212:in `transaction'
/app/app/models/ethscription.rb:36:in `process!'
/app/app/models/eth_block.rb:87:in `block (2 levels) in process_contract_actions_for_next_block_with_ethscriptions'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
/app/app/models/eth_block.rb:86:in `block in process_contract_actions_for_next_block_with_ethscriptions'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/usr/local/bundle/gems/activesupport-7.1.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/usr/local/bundle/gems/activerecord-7.1.2/lib/active_record/transactions.rb:212:in `transaction'
/app/app/models/eth_block.rb:70:in `process_contract_actions_for_next_block_with_ethscriptions'
/app/app/models/eth_block.rb:37:in `block in process_contract_actions_until_done'
/app/app/models/eth_block.rb:34:in `loop'
/app/app/models/eth_block.rb:34:in `process_contract_actions_until_done'
/app/config/processor_clock.rb:25:in `block in <module:Clockwork>'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/event.rb:61:in `execute'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/event.rb:48:in `run'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:136:in `block in tick'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:134:in `each'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:134:in `tick'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:123:in `block (2 levels) in run_tick_loop'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:121:in `synchronize'
/usr/local/bundle/gems/clockwork-3.0.2/lib/clockwork/manager.rb:121:in `block in run_tick_loop'
I, [2024-01-14T02:32:21.015038 #1]  INFO -- : Finished 'EthBlock.process_contract_actions_until_done' duration_ms=14 error=#<ActiveModel::UnknownAttributeError: unknown attribute 'call_level' for ContractCall.>
```

**Comment by dubuqingfeng** [comment]
I think database migration is necessary

bin/rails db:migrate

**Comment by dubuqingfeng** [comment]
It should be caused by this transaction:

https://etherscan.io/tx/0x7a825dded5040b95bf2a79484ba66dc60efde9de65f1f899d8726d87350d0a4c

**Comment by dubuqingfeng** [comment]
It's already normal.
